# -*- coding: utf-8 -*-
"""Yfin_DEMO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQ0OygT5PgFrfuxST5OT03TqcLVxVGv3

#Install yfinance & mplfinance
"""

pip install yfinance

pip install mplfinance

import yfinance as yf
import pandas as pd
import numpy as np
import mplfinance as mpl

"""#Fethcing Data from Yahoo Finance"""

data = yf.download('SAIL.NS', interval='1d')

data.columns

data.drop('Adj Close',axis=1,inplace=True)

data

"""#Ploting using mpl library"""

mpl.plot(data['2021-05':'2021-07'], title="SAIL", figratio=(30,12), type="ohlc",volume=True)

mpl.available_styles()

mpl.plot(data['2021-05':], title="SAIL INDIA",
         figratio=(30,12), type="candle", style='binance',
         mav=(20), volume=True)